services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Taipei
      - TZ=Asia/Taipei
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=true
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true      
      - N8N_SECURE_COOKIE=false
      # Disable TLS/HTTPS for lab
    volumes:
      - ./n8n_data:/home/node/.n8n
      # Persistent storage for workflows and data

volumes:
  n8n_data:
